language: cpp
matrix:
  include:
    - compiler: clang
      os: osx
      osx_image: xcode8.3
      env: SWIGLANG=ruby
    - compiler: clang
      os: osx
      osx_image: xcode9.3
      env: SWIGLANG=ruby

before_install:
  - $CC --version
  - $CXX --version

script:
  - export RUBYDIR=`(ruby -rrbconfig -e 'print RbConfig::CONFIG["rubyhdrdir"] || $rubyhdrdir') 2>/dev/null`
  - echo $RUBYDIR
  - export RUBYARCHHDRDIR=`(ruby -rrbconfig -e 'print RbConfig::CONFIG["rubyarchhdrdir"] || $rubyarchhdrdir') 2>/dev/null`
  - echo $RUBYARCHHDRDIR
  # warnings 1
  - g++ -I$RUBYDIR -I$RUBYARCHHDRDIR finitetest_ruby.cxx -o finitetest && ./finitetest || true
  - g++ -I$RUBYDIR -I$RUBYARCHHDRDIR finitetest_math.cxx -o finitetest && ./finitetest || true
  - g++ -I$RUBYDIR -I$RUBYARCHHDRDIR finitetest_ruby_math.cxx -o finitetest && ./finitetest || true
  - g++ -I$RUBYDIR -I$RUBYARCHHDRDIR finitetest_math_ruby.cxx -o finitetest && ./finitetest || true
  # warnings suppressed
  - g++ -I$RUBYDIR -I$RUBYARCHHDRDIR -Wno-deprecated-declarations finitetest_ruby.cxx -o finitetest && ./finitetest || true
