language: objective-c
env:
  - SWIGLANG=
#  - SWIGLANG= CC=clang CXX=clang++
matrix:
  include:
#    - env: SWIGLANG=csharp
#    - env: SWIGLANG=go
#    - env: SWIGLANG=guile
#    - env: SWIGLANG=java
#    - env: SWIGLANG=lua
# - env: SWIGLANG=octave SWIGJOBS=-j4
#    - env: SWIGLANG=perl5
#    - env: SWIGLANG=php
#    - env: SWIGLANG=python
#    - env: SWIGLANG=python PY3=1
#    - env: SWIGLANG=ruby
#    - env: SWIGLANG=tcl
  allow_failures:
      # None
before_install:
  - date -u
  - uname -a
  - sw_vers
  - brew update
#  - brew search guile
#  - brew versions guile
  - brew list
#  - brew search
#  - brew search guile
#  - brew versions guile
  - echo $PATH
  - ls -la $(which gcc)
  - ls -la $(which g++)
  - ls -la $(which gcc-4.2)
  - ls -la $(which g++-4.2)
  - gcc --version
  - gcc-4.2 --version
  - g++ --version
  - g++-4.2 --version
  - ls -la /usr/local/bin
  - ls -la /usr/bin
  - ls -la /bin
  - sudo ln -sf $(which gcc-4.2) $(which gcc)
  - sudo ln -sf $(which g++-4.2) $(which g++)
  - ls -la /usr/local/bin
  - ls -la $(which gcc)
  - ls -la $(which g++)
  - gcc --version
  - /usr/bin/gcc --version
  - g++ --version
  - /usr/bin/g++ --version
  - brew install pcre
  - brew install boost
  - if test "$SWIGLANG" = "csharp"; then brew install https://gist.github.com/shtirlic/4696903/raw/243c2f92961a285bb721aa67954c1efee4cd6a84/mono.rb; fi
  - if test "$SWIGLANG" = "go"; then brew install go && go env | sed -e 's/^/export /' > goenvsetup && source goenvsetup && rm -f goenvsetup; fi # Until configure.ac is fixed
  - if test "$SWIGLANG" = "guile"; then brew install guile; fi
  - if test "$SWIGLANG" = "lua"; then brew install lua; fi
  - if test "$SWIGLANG" = "python" -a "$PY3"; then brew install python3 && brew list -v python3; fi
script:
  - gcc --version
  - g++ --version
  - ./autogen.sh && ./configure CC=$CC CXX=$CXX
  - make -s $SWIGJOBS
  - ./swig -version
  - if test -z "$SWIGLANG"; then make -s check-ccache; fi
  - ./swig -pcreversion
  - if test -n "$SWIGLANG"; then make -s check-$SWIGLANG-version; fi
  - if test -n "$SWIGLANG"; then make -k $SWIGJOBS check-$SWIGLANG-examples; fi
  - if test -n "$SWIGLANG"; then make -k $SWIGJOBS check-$SWIGLANG-test-suite; fi
branches:
  only:
    - master
    - travis-osx
