
platform:
  - x86

configuration:
  - Release

install:
  - cinst winflexbison
  - cinst php

before_build:
  - cmd: dir
  - cmd: dir C:\MinGW
  - cmd: dir C:\MinGW\bin
  - cmd: dir C:\MinGW\msys
  - cmd: dir C:\MinGW\msys\bin
  - cmd: dir C:\MinGW\mingw32
  - cmd: php --version

build_script:
  - SET PATH=C:\MinGW\bin;C:\MinGW\msys\bin;%PATH%
  - bash ./autogen.sh
  - bash ./configure.sh
  - gcc --version
  - make --version
  - make -s

test_script:
  - make check-errors-test-suite

# Do not build on tags (GitHub only)
skip_tags: true 
