# Important to have C:\MinGW\bin at beginning of path as there is a version of bash in the default path
# TODO: where is it - with Git?
# This 32 bit version of MinGW doesn't seem to configured correctly, possibly because it is running on
# 64 bit Windows - direct.h does not compile off64_t is not defined and struct stat is missing.

os:
  - Unstable
#- Visual Studio 2014 CTP4
#- MinGW
#- Visual Studio 2015 CTP

platform:
  - x86

#
#configuration:
#  - Release
#
install:
  - date /T & time /T
  - set PATH=C:\cygwin\bin;%PATH%
#  - set PATH=C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
#  - cinst php
#  - set PATH=%PATH%;C:\tools\php
  - set PATH=C:\Python27;%PATH%
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86
  - set
  - dir C:\
  - dir C:\Python27
#  - dir C:\MinGW
#  - dir C:\MinGW\bin
#  - dir C:\MinGW\msys\1.0\bin

before_build:
  - gcc -v
  - make --version
#  - php.exe --version
#  - cygcheck -s
#  - set
  - uname -a

build_script:
#  - echo C:\MinGW /mingw >> C:\MinGW\msys\1.0\etc\fstab
#  - echo. >> C:\MinGW\msys\1.0\etc\fstab
#  - type C:\MinGW\msys\1.0\etc\fstab
  - bash -cl "ls -la C:/Libraries" || true
  - bash -cl "export CYGWIN=nodosfilewarning && ls -la C:/Libraries" || true
  - bash -cl "ls -la C:/Libraries" || true
  - bash -cl "echo $PATH"
#  - bash -cl "ls -la /; echo xx; ls -la /c; echo xxx; ls -la /mingw; true"
#  - bash -cl "mount; echo xx; ls /mingw/share/automake-1.11; echo xxx"
#  - bash -cl "set"
#  - bash -c "find C:/Libraries/boost -maxdepth 3 -type d || true"
#  - bash -c "find C:/Libraries/boost -maxdepth 3 -type f || true"
  - pwd
  - set JAVA_HOME=c:/Program Files (x86)/Java/jdk1.8.0
#  - set PATH=%JAVA_HOME%\bin;%PATH%
  - set PATH=%APPVEYOR_BUILD_FOLDER%\Tools\cccl;%PATH%
  - bash -c "which cl.exe || true"
  - bash -c "which csc.exe || true"
  - bash -c "cl.exe /? | head -n 2 || true"
  - bash -c "csc.exe /? | head -n 2 || true"
  - bash -c "which cccl || true"
  #Open dummy file descriptor to fix error: ./configure: line 560: 0: Bad file descriptor
  - bash -c "exec 0</dev/null && pwd && ./autogen.sh && ./configure --without-pcre CC=cccl CXX=cccl --with-java='%JAVA_HOME%/bin/java.exe' --with-javac='%JAVA_HOME%/bin/javac.exe' --with-javaincl='%JAVA_HOME%/include' --without-perl5 --without-go --with-boost=C:/Libraries/boost"
#  - bash -c "pwd && ./autogen.sh && ./configure --without-pcre CXXFLAGS='-g -O2 -Wall -Wextra' CFLAGS='-g -O2 -Wall -Wextra' --with-java='%JAVA_HOME%\\bin\\java.exe' --with-javac='%JAVA_HOME%\\bin\\javac.exe' --with-javaincl='%JAVA_HOME%\\include' --without-perl5 --without-go --with-boost-libdir=C:/Libraries/boost"
#  - bash -c "cat Source/Makefile || true"
  - bash -c "time make libfiles"
  - bash -c "time make -j2 source"
  - set CCCL_VERBOSE=1
  - bash -c "time make ccache || true"

test_script:
  - .\swig.exe -version
#  - .\ccache-swig.exe -V
#  - make check-errors-test-suite
#  - bash -c "make -k check-examples || true"
  - bash -c "make -k check-versions || true"
#  - bash -c "make -k check-java-test-suite || true"
#  - bash -c "cd Examples/test-suite/csharp && make allprotected.cpptest || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" || true"
#  - bash -c "echo 'cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec echo \"{}\" \\+ || true'"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec echo \"{}\" \\; || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec echo \"{}\" \\+ || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec cmd //c echo \"{}\" \\+ || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec p2w \"{}\" \\+ || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec msys_p2w \"{}\" \\+ || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec echo \"{}\" | sed -e \"s,\\\\\\\\,/,g\" \\; || true"
#  - bash -c "cd Examples/test-suite/csharp && find allprotected -name \"*.cs\" -exec echo \"{}\" | sed -e 's,\\\\,/,g' \\; || true"
#  - bash -c "grep -i cygpath Source/Makefile* || true"
#  - bash -c "make -k check-csharp-test-suite || true"
#  - bash -c "cat Examples/Makefile || true"
#  - bash -c "make -k check-csharp-examples || true"
  - bash -c "time make -k check-csharp-examples || true"
  - bash -c "time make -k check-java-examples || true"
#  - bash -c "make -k check-java-test-suite || true"

# Do not build on tags (GitHub only)
skip_tags: true 
