
platform:
  - x86

configuration:
  - Release

install:
  - date /T & time /T
#  - cinst php
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
#  - set PATH=%PATH%;C:\tools\php
  - set
  - dir C:\MinGW\bin
  - dir C:\MinGW\msys\1.0\bin

before_build:
  - gcc --version
  - make --version
#  - php.exe --version

build_script:
  - echo C:\MinGW /mingw > C:\MinGW\msys\1.0\etc\fstab
  - type C:\MinGW\msys\1.0\etc\fstab
  - path
  - type C:\MinGW\msys\1.0\msys.bat
  - C:\MinGW\msys\1.0\msys.bat
  - set
  - bash -cl "./autogen.sh && ./configure"
  - bash -cl "make"

test_script:
  - make check-errors-test-suite

# Do not build on tags (GitHub only)
skip_tags: true 
