version: 1.0.{build}
os:
- Windows Server 2012 R2
- MinGW
environment:
  matrix:
  - SWIGLANG: java
  - SWIGLANG: csharp
install:
- ps: >-
    If ($env:Platform -Match "x86") {
      $env:PCRE_PLATFORM="Win32"
      $env:JAVA_HOME="c:/Program Files (x86)/Java/jdk1.8.0"
      $env:VCVARS_PLATFORM="x86"
      $env:LANG_PLATFORM=""
    } Else {
      $env:PCRE_PLATFORM="x64"
      $env:JAVA_HOME="c:/Program Files/Java/jdk1.8.0"
      $env:VCVARS_PLATFORM="amd64"
      $env:LANG_PLATFORM="-x64"
    }
- echo variables...
- echo %PCRE_PLATFORM%
- echo %JAVA_HOME%
- echo %VCVARS_PLATFORM%
- echo LANG_PLATFORM%
build:
  verbosity: minimal
