
platform:
  - x86

configuration:
  - Release

install:
  - cinst winflexbison
  - cinst php
  - cinst mingw-get
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  - mingw-get install mingw-developer-toolkit

before_build:
  - cmd: dir
  - cmd: dir C:\MinGW
  - cmd: dir C:\MinGW\bin
  - cmd: dir C:\MinGW\msys
  - cmd: dir C:\MinGW\msys\bin
  - cmd: dir C:\MinGW\mingw32
  - cmd: php --version

build_script:
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
  - bash ./autogen.sh
  - bash ./configure.sh
  - gcc --version
  - make --version
  - make -s

test_script:
  - make check-errors-test-suite

# Do not build on tags (GitHub only)
skip_tags: true 
