
platform:
  - x86

configuration:
  - Release

install:
  - date /T & time /T
#  - cinst php
  - set PATH=%PATH%;C:\MinGW\msys\1.0\bin;C:\MinGW\bin
#  - set PATH=%PATH%;C:\tools\php
  - set
  - dir C:\MinGW
  - dir C:\MinGW\bin
  - dir C:\MinGW\msys\1.0\bin

before_build:
  - gcc --version
  - make --version
#  - php.exe --version

build_script:
  - echo C:\MinGW /mingw >> C:\MinGW\msys\1.0\etc\fstab
  - echo. >> C:\MinGW\msys\1.0\etc\fstab
  - type C:\MinGW\msys\1.0\etc\fstab
  - set
  - bash -cl "echo $PATH"
  - bash -cl "mount; echo xx; ls /mingw/share/automake-1.11; echo xxx; ls /usr/lib/perl5/5.8.8/msys; echo xxxx; ls  /usr/lib/perl5/5.8.8; ls /usr/lib/perl5/site_perl/5.8.8/msys; ls /usr/lib/perl5/site_perl/5.8.8; ls /usr/lib/perl5/site_perl"
  - dir "C:\MinGW\share\automake-1.11"
  - bash -cl "./autogen.sh && ./configure"
  - bash -cl "make"

test_script:
  - make check-errors-test-suite

# Do not build on tags (GitHub only)
skip_tags: true 
