platform:
- x86
- x64

environment:
  global:
    MAKEJOBS: 2

  matrix:
  - SWIGLANG: python
    VSVER: 14
    VER: 36
    PY3: 1

install:
- date /T & time /T
- ps: >-
    If ($env:Platform -Match "x86") {
      $env:PCRE_PLATFORM="Win32"
      $env:JAVA_HOME="C:/Program Files (x86)/Java/jdk1.8.0"
      $env:VCVARS_PLATFORM="x86"
      $env:LANG_PLATFORM=""
      $env:PATH="C:\cygwin\bin;$env:PATH"
    } Else {
      $env:PCRE_PLATFORM="x64"
      $env:JAVA_HOME="C:/Program Files/Java/jdk1.8.0"
      $env:VCVARS_PLATFORM="amd64"
      $env:LANG_PLATFORM="-x64"
      $env:PATH="C:\cygwin64\bin;$env:PATH"
    }
- set CYGWIN=nodosfilewarning
- git clone -q --depth=1 --single-branch --branch cccl-1.0 git://github.com/swig/cccl.git C:\cccl-1.0
- bash -c "cp C:/cccl-1.0/cccl /usr/bin"
- ps: $env:VSCOMNTOOLS=(Get-Content ("env:VS" + "$env:VSVER" + "0COMNTOOLS"))
- ps: echo "Using Visual Studio $env:VSVER.0 at $env:VSCOMNTOOLS"
- ps: . "$env:VSCOMNTOOLS\..\..\VC\vcvarsall.bat" $env:VCVARS_PLATFORM
- ps: Tools\nuget-install.cmd pcre -Verbosity quiet -Version 8.33.0.1 -OutputDirectory C:\pcre
- ps: $env:PCRE_ROOT=C:/pcre/pcre.8.33.0.1/build/native
- ps: $env:PATH=C:\Python$env:VER$env:LANG_PLATFORM;$env:PATH
- ps: python -V
- ps: bash -c "which python"
- ps: bash -c "python -V"
- ps: bash -c "which cl.exe"
- ps: bash -c "cl.exe /? 2>&1 | head -n 2"
- ps: bash -c "which csc.exe"
- ps: bash -c "csc.exe /? | head -n 2"
- ps: bash -c "which cccl"
- ps: bash -c "cccl --version"
- ps: make --version
- ps: uname -a

build_script:
- ps: $env:CCCL_OPTIONS=--cccl-muffle /W3
- ps: $env:CHECK_OPTIONS=CSHARPOPTIONS=-platform:$env:Platform
  # Open dummy file descriptor to fix error on cygwin: ./configure: line 560: 0: Bad file descriptor
- ps: echo "exec 0</dev/null && ./autogen.sh && time ./configure --disable-dependency-tracking --disable-ccache CC=cccl CXX=cccl CFLAGS='-O2' CXXFLAGS='-O2' LDFLAGS='--cccl-link /LTCG' PCRE_CFLAGS='-I$env:PCRE_ROOT/include -DPCRE_STATIC' PCRE_LIBS='-L$env:PCRE_ROOT/lib/v110/$env:PCRE_PLATFORM/Release/static/utf8 -lpcre8' --without-perl5 --without-go --with-boost=C:/Libraries/boost || cat config.log"
- ps: bash -c "exec 0</dev/null && ./autogen.sh && time ./configure --disable-dependency-tracking --disable-ccache CC=cccl CXX=cccl CFLAGS='-O2' CXXFLAGS='-O2' LDFLAGS='--cccl-link /LTCG' PCRE_CFLAGS='-I$env:PCRE_ROOT/include -DPCRE_STATIC' PCRE_LIBS='-L$env:PCRE_ROOT/lib/v110/$env:PCRE_PLATFORM/Release/static/utf8 -lpcre8' --without-perl5 --without-go --with-boost=C:/Libraries/boost || cat config.log"
- ps: bash -c "time make -s -j$env:MAKEJOBS"

test_script:
- ps: $env:CCCL_OPTIONS=--cccl-muffle /W3 /EHsc
# (Warning below is fixed in newer versions of Python (2.7.9)) '_hypot' : recursive on all control paths, function will cause runtime stack overflow
- ps: >-
    If ("$env:SWIGLANG$env:VER" -Match "python27") {
      $env:CCCL_OPTIONS="$env:CCCL_OPTIONS /wd4717"
    }
- .\swig.exe -version
- ps: bash -c "file ./swig.exe"
- ps: bash -c "time make -k check-$env:SWIGLANG-version"
- ps: bash -c "time make -k check-$env:SWIGLANG-examples $env:CHECK_OPTIONS"
- ps: bash -c "time make -k check-$env:SWIGLANG-test-suite -j$env:MAKEJOBS $env:CHECK_OPTIONS"

# Do not build on tags (GitHub only)
skip_tags: true
