name: CI

on:
  push:
    paths-ignore:
      - 'CHANGES*'
      - 'Doc/**'
      - 'appveyor.yml'
  pull_request:
    branches: master
    paths-ignore:
      - 'CHANGES*'
      - 'Doc/**'
      - 'appveyor.yml'

jobs:
  build:

    # continue-on-error: true
    runs-on: ${{ matrix.os || 'ubuntu-20.04' }}

    # By default, the name of the build is the language used and SWIG options, but matrix entries
    # can define the additional "desc" field with any additional information to include in the name.
    name: ${{ matrix.SWIGLANG || 'none' }}${{ matrix.PY3 }} ${{ matrix.ENGINE}} ${{ matrix.VER }} ${{ matrix.SWIG_FEATURES }} ${{ (matrix.GCC && 'gccisset') || 'gccnotset' }} ${{ matrix.desc }}

    strategy:
      matrix:
        include:
        # c++11 testing
#       - SWIGLANG: csharp
#         CPP11: 1
        - SWIGLANG: go
          VER: '1.14'
          CPP11: 1
          CSTD: gnu11
        - SWIGLANG: go
          VER: '1.15'
          CPP11: 1
          CSTD: gnu11
        - SWIGLANG: go
          VER: '1.16'
          CPP11: 1
          CSTD: gnu11
        - SWIGLANG: go
          VER: '1.17'
          CPP11: 1
          CSTD: gnu11
        - SWIGLANG: go
          VER: '1.16'
          CPP11: 1
          CSTD: gnu99
#       - SWIGLANG: java
#         CPP11: 1
#       - SWIGLANG: javascript
#         ENGINE: node
#         VER: '14'
#         CPP11: 1
#       - SWIGLANG: octave
#         CPP11: 1
#       - SWIGLANG: perl5
#         CPP11: 1
        - SWIGLANG: php
          CPP11: 1
          CSTD: gnu11
          os: ubuntu-18.04
        - SWIGLANG: php
          CPP11: 1
          os: ubuntu-18.04
        - SWIGLANG: php
          VER: '8.0'
          CPP11: 1
          os: ubuntu-18.04
        - SWIGLANG: php
          VER: '7.4'
          CPP11: 1
          os: ubuntu-18.04
#       - SWIGLANG: python
#         CPP11: 1
#         PY3: 3
#       - SWIGLANG: r
#         CPP11: 1
#       - SWIGLANG: ruby
#         CPP11: 1
#       - SWIGLANG: tcl
#         CPP11: 1
#       # c++14 testing
#       - SWIGLANG: csharp
#         CPP14: 1
        - SWIGLANG: go
          VER: '1.16'
          CPP14: 1
          CSTD: gnu11
#       - SWIGLANG: java
#         CPP14: 1
#       - SWIGLANG: javascript
#         ENGINE: node
#         VER: '16'
#         CPP14: 1
#       - SWIGLANG: octave
#         CPP14: 1
#       - SWIGLANG: perl5
#         CPP14: 1
        - SWIGLANG: php
          VER: '7.4'
          CPP14: 1
          os: ubuntu-18.04
#       - SWIGLANG: python
#         CPP14: 1
#         PY3: 3
#       - SWIGLANG: r
#         CPP14: 1
#       - SWIGLANG: ruby
#         CPP14: 1
#       - SWIGLANG: tcl
#         CPP14: 1
#       # c++17 testing
#       - SWIGLANG: csharp
#         CPP17: 1
#         GCC: 11
        - SWIGLANG: go
          VER: '1.16'
          CPP17: 1
          GCC: 11
#         CSTD: gnu17
#       - SWIGLANG: java
#         CPP17: 1
#         GCC: 11
#       - SWIGLANG: javascript
#         ENGINE: node
#         VER: '16'
#         CPP17: 1
#         GCC: 11
#       - SWIGLANG: octave
#         CPP17: 1
#         GCC: 11
#       - SWIGLANG: perl5
#         CPP17: 1
#         GCC: 11
        - SWIGLANG: php
          VER: '7.4'
          CPP17: 1
          GCC: 11
          os: ubuntu-18.04
#       - SWIGLANG: python
#         CPP17: 1
#         GCC: 11
#         PY3: 3
#       - SWIGLANG: r
#         CPP17: 1
#         GCC: 11
#       - SWIGLANG: ruby
#         CPP17: 1
#         GCC: 11
#       - SWIGLANG: tcl
#         CPP17: 1
#         GCC: 11
        # let's run all of them, as opposed to aborting when one fails
      fail-fast: false

    env:
      SWIGLANG: ${{ matrix.SWIGLANG }}
      PY3: ${{ matrix.PY3 }}
      VER: ${{ matrix.VER }}
      ENGINE: ${{ matrix.ENGINE }}
      SWIG_FEATURES: ${{ matrix.SWIG_FEATURES }}
      CSTD: ${{ matrix.CSTD }}
      CPP11: ${{ matrix.CPP11 }}
      CPP14: ${{ matrix.CPP14 }}
      CPP17: ${{ matrix.CPP17 }}
      GCC: ${{ matrix.GCC }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install CCache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.os || 'ubuntu-20.04' }}-${{ matrix.compiler || 'gcc' }}${{ matrix.GCC }}

    - name: Install Dependencies
      run: |
          set -x
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          echo PATH="$PATH" >> $GITHUB_ENV

          source $GITHUB_WORKSPACE/Tools/GHA-linux-install.sh
          echo WITHLANG="$WITHLANG" >> $GITHUB_ENV

          case $(uname) in
              Linux)
                  cpu_count=$(nproc)
                  ;;

              Darwin)
                  cpu_count=$(sysctl -n hw.ncpu)
                  ;;

              *)
                  cpu_count=1
                  ;;
          esac

          if [[ $cpu_count != 1 ]]; then
            echo SWIGJOBS=-j$cpu_count >> $GITHUB_ENV
          fi

          if test '${{ matrix.compiler }}' = 'clang'; then
            CC="clang"
            CXX="clang++"

            CFLAGS="$CFLAGS -fPIE"
            CXXFLAGS="$CXXFLAGS -fPIE"
          elif test -n "$GCC"; then
            CC="gcc-$GCC"
            CXX="g++-$GCC"
          else
            CC="gcc"
            CXX="g++"
          fi

          export CC CXX

          echo CC="$CC" >> $GITHUB_ENV
          echo CXX="$CXX" >> $GITHUB_ENV

          ls -la $(which $CC) $(which $CXX)
          $CC --version
          $CXX --version

    - name: Configure
      run: |
          source $GITHUB_WORKSPACE/Tools/CI-linux-environment.sh
          set -x

          if test -n "$CPP11"; then export CPPSTD=c++11 && export CSTD=c11; fi
          if test -n "$CPP14"; then export CPPSTD=c++14 && export CSTD=c11; fi
          if test -n "$CPP17"; then export CPPSTD=c++17 && export CSTD=c17; fi
          echo CPPSTD="$CPPSTD" >> $GITHUB_ENV
          echo CSTD="$CSTD" >> $GITHUB_ENV

          if test -n '${{ matrix.CONFIGOPTS }}'; then
            CONFIGOPTS=${{ matrix.CONFIGOPTS }}
          fi
          if test -n "$CPP11"; then CONFIGOPTS+=(--enable-cpp11-testing "CXXFLAGS=-std=c++11 $CXXFLAGS" "CFLAGS=-std=c11 $CFLAGS"); fi
          if test -n "$CPP14"; then CONFIGOPTS+=(--enable-cpp11-testing "CXXFLAGS=-std=c++14 $CXXFLAGS" "CFLAGS=-std=c11 $CFLAGS"); fi
          if test -n "$CPP17"; then CONFIGOPTS+=(--enable-cpp11-testing "CXXFLAGS=-std=c++17 $CXXFLAGS" "CFLAGS=-std=c17 $CFLAGS"); fi
          if test -n "$SWIGLANG"; then CONFIGOPTS+=(--without-alllang --with-$WITHLANG); fi
          echo "${CONFIGOPTS[@]}"
          ./autogen.sh && mkdir -p build/build && cd build/build && ../../configure "${CONFIGOPTS[@]}"

    - name: Build
      working-directory: build/build
      run: |
          set -x
          make -s $SWIGJOBS
          ./swig -version && ./swig -pcreversion

    - name: Test
      working-directory: build/build
      run: |
          source $GITHUB_WORKSPACE/Tools/CI-linux-environment.sh
          set -x

          if test -z "$SWIGLANG"; then make $SWIGJOBS check-ccache; fi
          if test -z "$SWIGLANG"; then make $SWIGJOBS check-errors-test-suite; fi

          case "$SWIGLANG" in
            javascript)
              case "$ENGINE" in
                v8 | jsc)
                  # Running tests using v8 or jsc involves creating a custom
                  # interpreter in Tools/javascript, which is currently broken
                  # for parallel builds (we attempt to update this interpreter
                  # while running, resulting in "Text file busy" error).
                  unset SWIGJOBS
              esac
              ;;
          esac

          # Stricter compile flags for examples. Various headers and SWIG generated code prevents full use of -pedantic.
          if test -n "$SWIGLANG"; then cflags=$($GITHUB_WORKSPACE/Tools/testflags.py --language $SWIGLANG --cflags --std=$CSTD --compiler=$CC) && echo $cflags; fi
          if test -n "$SWIGLANG"; then cxxflags=$($GITHUB_WORKSPACE/Tools/testflags.py --language $SWIGLANG --cxxflags --std=$CPPSTD --compiler=$CC) && echo $cxxflags; fi
          if test -n "$SWIGLANG"; then make check-$SWIGLANG-version; fi
          if test -n "$SWIGLANG"; then make check-$SWIGLANG-enabled; fi
          if test -n "$SWIGLANG"; then make $SWIGJOBS check-$SWIGLANG-examples CFLAGS="$cflags" CXXFLAGS="$cxxflags"; fi
          if test -n "$SWIGLANG"; then make $SWIGJOBS check-$SWIGLANG-test-suite CFLAGS="$cflags" CXXFLAGS="$cxxflags"; fi

    - name: Install
      working-directory: build/build
      run: |
          set -x
          if test -z "$SWIGLANG"; then sudo make install && swig -version && ccache-swig -V; fi

    - name: Clean
      working-directory: build/build
      run: |
          set -x
          make check-maintainer-clean && ../../configure $CONFIGOPTS
